package testing;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;

public class TestAutogeneratedId {
	
	public TestAutogeneratedId(){
		
		Entity[] ent = new Entity[10];		

		DatastoreService ds = DatastoreServiceFactory.getDatastoreService();
		for (int i = 0; i < ent.length; i++) {
			ent[i] =  new Entity("kind_"+i);
			ent[i].setProperty("p"+i, i);	
			ds.put(ent[i]);
		}
		
	}

}
